name: Release

on:
  push:

jobs:
  create_env_file:
    runs-on: ubuntu-latest
    steps:
      - uses: skiddph/actions-env@v1.0.2
        with:
          file: .env
          prefix: "ENV_"
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}

  release:
    needs: create_env_file
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: falti/dotenv-action@v1.0.2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run tsc
      - run: npm run test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
