name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: falti/dotenv-action@v1.0.2
        with:
          node-version: 18
      - name: "Create env file"
        run: |
          echo "${{ secrets.MONGO_URI }}" > .env
          echo "${{ secrets.PORT }}" > .env
      - run: npm ci
      - run: npm run test
      - run: npm run tsc
